/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package res2_laundry;

/**
 *
 * @author Fery Eka Mahendra
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public final class res2_laundry extends javax.swing.JFrame {

    /**
     * Creates new form res2_laundry
     */
    private String sql;
    private Connection con;
    private Statement st;
    private ResultSet rs;
    private PreparedStatement ps;
    private DefaultTableModel dtm;
    public int harga, berat, bayar;

    public void koneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_laundry", "root", "");
            jLabelstatus.setText("TERSAMBUNG");
        } catch (Exception e) {
            jLabelstatus.setText("TIDAK TERSAMBUNG");
        }
    }

    private void tanggal() {
        Date ys = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        jTexttgl.setText(s.format(ys));
    }

    public res2_laundry() {
        initComponents();
        koneksi();
        tanggal();
        setExtendedState(MAXIMIZED_BOTH);
    }

    public void kosong() {
        jTextkode.setText("");
        jTextberat.setText("");
        jTexttelp.setText("");
        jTexttotal.setText("");
        jTextnama.setText("");
        jTextalamat.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTexttgl = new javax.swing.JTextField();
        jTextkode = new javax.swing.JTextField();
        jTextnama = new javax.swing.JTextField();
        jTexttelp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextalamat = new javax.swing.JTextArea();
        jTextberat = new javax.swing.JTextField();
        jTextharga = new javax.swing.JTextField();
        jTexttotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelstatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTexttgl.setEditable(false);
        getContentPane().add(jTexttgl);
        jTexttgl.setBounds(130, 50, 110, 30);
        getContentPane().add(jTextkode);
        jTextkode.setBounds(130, 90, 110, 30);
        getContentPane().add(jTextnama);
        jTextnama.setBounds(130, 130, 110, 30);
        getContentPane().add(jTexttelp);
        jTexttelp.setBounds(130, 170, 110, 30);

        jTextalamat.setColumns(20);
        jTextalamat.setRows(5);
        jScrollPane1.setViewportView(jTextalamat);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 210, 240, 100);

        jTextberat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextberatActionPerformed(evt);
            }
        });
        getContentPane().add(jTextberat);
        jTextberat.setBounds(400, 50, 110, 30);

        jTextharga.setEditable(false);
        jTextharga.setText("6000");
        getContentPane().add(jTextharga);
        jTextharga.setBounds(400, 90, 110, 30);
        getContentPane().add(jTexttotal);
        jTexttotal.setBounds(400, 130, 110, 30);

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(530, 50, 73, 23);

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(620, 50, 73, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 320, 730, 150);

        jButton3.setText("Simpan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(370, 290, 73, 23);

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(460, 290, 73, 23);

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(550, 290, 73, 23);

        jButton6.setText("View");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(640, 290, 73, 23);

        jLabel1.setText("Tanggal");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 50, 50, 14);

        jLabel2.setText("Kode Pelanggan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 90, 110, 14);

        jLabel3.setText("Nama Pelanggan");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 130, 110, 14);

        jLabel4.setText("No Telp");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 170, 50, 14);

        jLabel5.setText("Alamat");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 210, 50, 14);

        jLabel6.setText("Berat Pakaian (kg)");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(280, 50, 120, 14);

        jLabel7.setText("Harga /kg");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(280, 90, 70, 14);

        jLabel8.setText("Total Bayar");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(280, 130, 70, 14);

        jLabel9.setText("Status Koneksi DB :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(470, 10, 110, 20);
        getContentPane().add(jLabelstatus);
        jLabelstatus.setBounds(590, 10, 140, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextberatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextberatActionPerformed
        // TODO add your handling code here:
        berat = Integer.parseInt(jTextberat.getText());
        harga = 6000;
        bayar = berat * 6000;
        jTexttotal.setText(String.valueOf(bayar));
        jTextharga.setText(String.valueOf(harga));
    }//GEN-LAST:event_jTextberatActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            sql = "insert into laundry values('" + jTexttgl.getText() + "',"
                    + "'" + jTextkode.getText() + "','" + jTextnama.getText() + "',"
                    + "'" + jTexttelp.getText() + "','" + jTextalamat.getText() + "',"
                    + "'" + jTextberat.getText() + "','" + jTextharga.getText() + "','" + jTexttotal.getText() + "')";
            st = con.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data Berhasil Tersimpan");
            kosong();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Tersimpan");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try {
            Object[] rows = {"NO", "TANGGAL", "KODE PELANGGAN", "NAMA PELANGGAN", "NO TELP", "ALAMAT", "BERAT PAKAIAN", "HARGA", "TOTAL BAYAR"};

            dtm = new DefaultTableModel(null, rows);
            jTable1.setModel(dtm);
            jTable1.setBorder(null);
            jScrollPane2.setVisible(true);
            jScrollPane2.setViewportView(jTable1);
            int a = 1;
            String tgl = "", kode = "", nama = "", no = "", alamat = "", berat = "", harga = "", bayar = "";
            try {
                String sql = "SELECT * FROM laundry";
                st = con.createStatement();
                rs = st.executeQuery(sql);
                while (rs.next()) {
                    tgl = rs.getString("Tanggal");
                    kode = rs.getString("KdPelanggan");
                    nama = rs.getString("Nama_Pelanggan");
                    no = rs.getString("NoTelp");
                    alamat = rs.getString("Alamat");
                    berat = rs.getString("BeratPakaian");
                    harga = rs.getString("Harga");
                    bayar = rs.getString("TotalBayar");

                    String[] tampil = {"" + a++, tgl, kode, nama, no, alamat, berat, harga, bayar};
                    dtm.addRow(tampil);

                }
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Query Salah" + e);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        jTexttgl.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
        jTextkode.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        jTextnama.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
        jTexttelp.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
        jTextalamat.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
        jTextberat.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
        jTextharga.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());
        jTexttotal.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString());

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Data Anda Akan Dirubah?", "Konfirmasi Update", JOptionPane.YES_NO_OPTION);
        try {
            sql = "update laundry set Tanggal=?,KdPelanggan=?,Nama_Pelanggan=?,NoTelp=?,"
                    + "Alamat=?,BeratPakaian=?,Harga=?,TotalBayar=? where KdPelanggan='" + jTextkode.getText() + "'";
            PreparedStatement edit = con.prepareStatement(sql);
            if (ok == 0) {
                try {

                    edit.setString(1, jTexttgl.getText());
                    edit.setString(2, jTextkode.getText());
                    edit.setString(3, jTextnama.getText());
                    edit.setString(4, jTexttelp.getText());
                    edit.setString(5, jTextalamat.getText());
                    edit.setString(6, jTextberat.getText());
                    edit.setString(7, jTextharga.getText());
                    edit.setString(8, jTexttotal.getText());

                    edit.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Update Data Berhasil");

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Update Data Tidak Berhasil");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "TABEL SALAH");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Yakin Data Anda Akan Dihapus?", "Konfirmasi DELETE", JOptionPane.YES_NO_OPTION);
        if(ok==0){
            try{
                sql="delete from laundry where KdPelanggan='"+jTextkode.getText()+"'";
                PreparedStatement st=con.prepareStatement(sql);
                st.executeUpdate();
                JOptionPane.showMessageDialog(null,"DATA ANDA BERHASIL DIHAPUS");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"DATA ANDA TIDAK BERHASIL DIHAPUS");
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(res2_laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(res2_laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(res2_laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(res2_laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new res2_laundry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelstatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextalamat;
    private javax.swing.JTextField jTextberat;
    private javax.swing.JTextField jTextharga;
    private javax.swing.JTextField jTextkode;
    private javax.swing.JTextField jTextnama;
    private javax.swing.JTextField jTexttelp;
    private javax.swing.JTextField jTexttgl;
    private javax.swing.JTextField jTexttotal;
    // End of variables declaration//GEN-END:variables
}
